//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Handwriting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Handwriting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images {
            get {
                object obj = ResourceManager.GetObject("images", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__6_ {
            get {
                object obj = ResourceManager.GetObject("images (6)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap images__6_1 {
            get {
                object obj = ResourceManager.GetObject("images (6)1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap kids_handwriting {
            get {
                object obj = ResourceManager.GetObject("kids-handwriting", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000000000000000000000000000
        ///0000000000000000000000000000
        ///0000000000000000000000000000
        ///0000000000000000000000000000
        ///0000000000000000000000000000
        ///0000000000001111111111110000
        ///0000000011111111111111110000
        ///0000000111111111111111100000
        ///0000000111111111110000000000
        ///0000000011111110110000000000
        ///0000000001111100000000000000
        ///0000000000011110000000000000
        ///0000000000011110000000000000
        ///0000000000001111110000000000
        ///0000000000000111111000000000
        ///0000000000000011111100000000
        ///0000000000000001111100000000
        ///00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string myDataset_txt {
            get {
                return ResourceManager.GetString("myDataset.txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000000000000000000000000000
        ///0000000000000000000000000000
        ///0000000000000000000000000000
        ///0000000000000000000000000000
        ///0000000000000000000000000000
        ///0000000000000000000000000000
        ///0000000000000000000000000000
        ///0000001111110000000000000000
        ///0000001111111111111111000000
        ///0000001111111111111111000000
        ///0000000000011111111111000000
        ///0000000000000000001111000000
        ///0000000000000000011110000000
        ///0000000000000000011110000000
        ///0000000000000000111100000000
        ///0000000000000000111100000000
        ///0000000000000001111000000000
        ///00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestDataset_txt {
            get {
                return ResourceManager.GetString("TestDataset.txt", resourceCulture);
            }
        }
    }
}
